/* Auto-generated by genmsg_cpp for file /home/wangkuan/workspace/ORB_SLAM2/ORB_SLAM2/Examples/ROS/ORB_SLAM2/msg/bow.msg */
#ifndef ORB_SLAM2_MESSAGE_BOW_H
#define ORB_SLAM2_MESSAGE_BOW_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace ORB_SLAM2
{
template <class ContainerAllocator>
struct bow_ {
  typedef bow_<ContainerAllocator> Type;

  bow_()
  : WordId(0)
  , WordValue(0.0)
  {
  }

  bow_(const ContainerAllocator& _alloc)
  : WordId(0)
  , WordValue(0.0)
  {
  }

  typedef uint32_t _WordId_type;
  uint32_t WordId;

  typedef double _WordValue_type;
  double WordValue;


  typedef boost::shared_ptr< ::ORB_SLAM2::bow_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ORB_SLAM2::bow_<ContainerAllocator>  const> ConstPtr;
}; // struct bow
typedef  ::ORB_SLAM2::bow_<std::allocator<void> > bow;

typedef boost::shared_ptr< ::ORB_SLAM2::bow> bowPtr;
typedef boost::shared_ptr< ::ORB_SLAM2::bow const> bowConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ORB_SLAM2::bow_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ORB_SLAM2::bow_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ORB_SLAM2

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ORB_SLAM2::bow_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ORB_SLAM2::bow_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ORB_SLAM2::bow_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f78cbe6c36bf20a84ed4ac76d310ff0f";
  }

  static const char* value(const  ::ORB_SLAM2::bow_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xf78cbe6c36bf20a8ULL;
  static const uint64_t static_value2 = 0x4ed4ac76d310ff0fULL;
};

template<class ContainerAllocator>
struct DataType< ::ORB_SLAM2::bow_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ORB_SLAM2/bow";
  }

  static const char* value(const  ::ORB_SLAM2::bow_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ORB_SLAM2::bow_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint32   WordId\n\
float64  WordValue\n\
\n\
";
  }

  static const char* value(const  ::ORB_SLAM2::bow_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::ORB_SLAM2::bow_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ORB_SLAM2::bow_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.WordId);
    stream.next(m.WordValue);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct bow_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ORB_SLAM2::bow_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ORB_SLAM2::bow_<ContainerAllocator> & v) 
  {
    s << indent << "WordId: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.WordId);
    s << indent << "WordValue: ";
    Printer<double>::stream(s, indent + "  ", v.WordValue);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ORB_SLAM2_MESSAGE_BOW_H

