/* Auto-generated by genmsg_cpp for file /home/wangkuan/workspace/ORB_SLAM2/ORB_SLAM2/Examples/ROS/ORB_SLAM2/msg/descriptor.msg */
#ifndef ORB_SLAM2_MESSAGE_DESCRIPTOR_H
#define ORB_SLAM2_MESSAGE_DESCRIPTOR_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace ORB_SLAM2
{
template <class ContainerAllocator>
struct descriptor_ {
  typedef descriptor_<ContainerAllocator> Type;

  descriptor_()
  : descriptor()
  {
  }

  descriptor_(const ContainerAllocator& _alloc)
  : descriptor(_alloc)
  {
  }

  typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _descriptor_type;
  std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  descriptor;


  typedef boost::shared_ptr< ::ORB_SLAM2::descriptor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ORB_SLAM2::descriptor_<ContainerAllocator>  const> ConstPtr;
}; // struct descriptor
typedef  ::ORB_SLAM2::descriptor_<std::allocator<void> > descriptor;

typedef boost::shared_ptr< ::ORB_SLAM2::descriptor> descriptorPtr;
typedef boost::shared_ptr< ::ORB_SLAM2::descriptor const> descriptorConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ORB_SLAM2::descriptor_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ORB_SLAM2::descriptor_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ORB_SLAM2

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ORB_SLAM2::descriptor_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ORB_SLAM2::descriptor_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ORB_SLAM2::descriptor_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0404998a9bdc9e99a1076385c9fa7816";
  }

  static const char* value(const  ::ORB_SLAM2::descriptor_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0404998a9bdc9e99ULL;
  static const uint64_t static_value2 = 0xa1076385c9fa7816ULL;
};

template<class ContainerAllocator>
struct DataType< ::ORB_SLAM2::descriptor_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ORB_SLAM2/descriptor";
  }

  static const char* value(const  ::ORB_SLAM2::descriptor_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ORB_SLAM2::descriptor_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint8[] descriptor\n\
\n\
";
  }

  static const char* value(const  ::ORB_SLAM2::descriptor_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ORB_SLAM2::descriptor_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.descriptor);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct descriptor_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ORB_SLAM2::descriptor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ORB_SLAM2::descriptor_<ContainerAllocator> & v) 
  {
    s << indent << "descriptor[]" << std::endl;
    for (size_t i = 0; i < v.descriptor.size(); ++i)
    {
      s << indent << "  descriptor[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.descriptor[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // ORB_SLAM2_MESSAGE_DESCRIPTOR_H

