/* Auto-generated by genmsg_cpp for file /home/wangkuan/workspace/ORB_SLAM2/ORB_SLAM2/Examples/ROS/ORB_SLAM2/msg/floatVector.msg */
#ifndef ORB_SLAM2_MESSAGE_FLOATVECTOR_H
#define ORB_SLAM2_MESSAGE_FLOATVECTOR_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace ORB_SLAM2
{
template <class ContainerAllocator>
struct floatVector_ {
  typedef floatVector_<ContainerAllocator> Type;

  floatVector_()
  : floatVector()
  {
  }

  floatVector_(const ContainerAllocator& _alloc)
  : floatVector(_alloc)
  {
  }

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _floatVector_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  floatVector;


  typedef boost::shared_ptr< ::ORB_SLAM2::floatVector_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ORB_SLAM2::floatVector_<ContainerAllocator>  const> ConstPtr;
}; // struct floatVector
typedef  ::ORB_SLAM2::floatVector_<std::allocator<void> > floatVector;

typedef boost::shared_ptr< ::ORB_SLAM2::floatVector> floatVectorPtr;
typedef boost::shared_ptr< ::ORB_SLAM2::floatVector const> floatVectorConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ORB_SLAM2::floatVector_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ORB_SLAM2::floatVector_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ORB_SLAM2

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ORB_SLAM2::floatVector_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ORB_SLAM2::floatVector_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ORB_SLAM2::floatVector_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0f0363c304aa90017dbf08933366514c";
  }

  static const char* value(const  ::ORB_SLAM2::floatVector_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0f0363c304aa9001ULL;
  static const uint64_t static_value2 = 0x7dbf08933366514cULL;
};

template<class ContainerAllocator>
struct DataType< ::ORB_SLAM2::floatVector_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ORB_SLAM2/floatVector";
  }

  static const char* value(const  ::ORB_SLAM2::floatVector_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ORB_SLAM2::floatVector_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64[] floatVector\n\
\n\
";
  }

  static const char* value(const  ::ORB_SLAM2::floatVector_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ORB_SLAM2::floatVector_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.floatVector);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct floatVector_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ORB_SLAM2::floatVector_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ORB_SLAM2::floatVector_<ContainerAllocator> & v) 
  {
    s << indent << "floatVector[]" << std::endl;
    for (size_t i = 0; i < v.floatVector.size(); ++i)
    {
      s << indent << "  floatVector[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.floatVector[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // ORB_SLAM2_MESSAGE_FLOATVECTOR_H

