/* Auto-generated by genmsg_cpp for file /home/wangkuan/workspace/ORB_SLAM2/ORB_SLAM2/Examples/ROS/ORB_SLAM2/msg/float32Vector.msg */
#ifndef ORB_SLAM2_MESSAGE_FLOAT32VECTOR_H
#define ORB_SLAM2_MESSAGE_FLOAT32VECTOR_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace ORB_SLAM2
{
template <class ContainerAllocator>
struct float32Vector_ {
  typedef float32Vector_<ContainerAllocator> Type;

  float32Vector_()
  : float32Vector()
  {
  }

  float32Vector_(const ContainerAllocator& _alloc)
  : float32Vector(_alloc)
  {
  }

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _float32Vector_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  float32Vector;


  typedef boost::shared_ptr< ::ORB_SLAM2::float32Vector_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ORB_SLAM2::float32Vector_<ContainerAllocator>  const> ConstPtr;
}; // struct float32Vector
typedef  ::ORB_SLAM2::float32Vector_<std::allocator<void> > float32Vector;

typedef boost::shared_ptr< ::ORB_SLAM2::float32Vector> float32VectorPtr;
typedef boost::shared_ptr< ::ORB_SLAM2::float32Vector const> float32VectorConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ORB_SLAM2::float32Vector_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ORB_SLAM2::float32Vector_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ORB_SLAM2

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ORB_SLAM2::float32Vector_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ORB_SLAM2::float32Vector_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ORB_SLAM2::float32Vector_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f48d72fee5a47e085b6e6bc3153f6f0e";
  }

  static const char* value(const  ::ORB_SLAM2::float32Vector_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xf48d72fee5a47e08ULL;
  static const uint64_t static_value2 = 0x5b6e6bc3153f6f0eULL;
};

template<class ContainerAllocator>
struct DataType< ::ORB_SLAM2::float32Vector_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ORB_SLAM2/float32Vector";
  }

  static const char* value(const  ::ORB_SLAM2::float32Vector_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ORB_SLAM2::float32Vector_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32[] float32Vector\n\
\n\
";
  }

  static const char* value(const  ::ORB_SLAM2::float32Vector_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ORB_SLAM2::float32Vector_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.float32Vector);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct float32Vector_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ORB_SLAM2::float32Vector_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ORB_SLAM2::float32Vector_<ContainerAllocator> & v) 
  {
    s << indent << "float32Vector[]" << std::endl;
    for (size_t i = 0; i < v.float32Vector.size(); ++i)
    {
      s << indent << "  float32Vector[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.float32Vector[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // ORB_SLAM2_MESSAGE_FLOAT32VECTOR_H

