# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ORB_SLAM2/keypoint.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class keypoint(genpy.Message):
  _md5sum = "41e5e28e60265f1705aaf1fd0e42dee5"
  _type = "ORB_SLAM2/keypoint"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 x
int32 y
float32 angle
int32 class_id
int32 octave
float32 response
float32 size
"""
  __slots__ = ['x','y','angle','class_id','octave','response','size']
  _slot_types = ['int32','int32','float32','int32','int32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,y,angle,class_id,octave,response,size

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(keypoint, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = 0
      if self.y is None:
        self.y = 0
      if self.angle is None:
        self.angle = 0.
      if self.class_id is None:
        self.class_id = 0
      if self.octave is None:
        self.octave = 0
      if self.response is None:
        self.response = 0.
      if self.size is None:
        self.size = 0.
    else:
      self.x = 0
      self.y = 0
      self.angle = 0.
      self.class_id = 0
      self.octave = 0
      self.response = 0.
      self.size = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2if2i2f().pack(_x.x, _x.y, _x.angle, _x.class_id, _x.octave, _x.response, _x.size))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.x, _x.y, _x.angle, _x.class_id, _x.octave, _x.response, _x.size,) = _get_struct_2if2i2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2if2i2f().pack(_x.x, _x.y, _x.angle, _x.class_id, _x.octave, _x.response, _x.size))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.x, _x.y, _x.angle, _x.class_id, _x.octave, _x.response, _x.size,) = _get_struct_2if2i2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2if2i2f = None
def _get_struct_2if2i2f():
    global _struct_2if2i2f
    if _struct_2if2i2f is None:
        _struct_2if2i2f = struct.Struct("<2if2i2f")
    return _struct_2if2i2f
